### ISSUE TITLE
这个主题有几个bug

### ISSUE THREAD

**Issue by huclengyue** [ArianeLu/LunarLoveS#1]
![](http://i3.tietuku.com/f1081bc083bb196c.jpg)
这个文字不能居中，不晓得为什么

![](http://i3.tietuku.com/77617b8bd1494734.jpg)

这个把导航栏挡住了··

另外这个色调在哪里能调呢？ 你要知道一个男生用粉红色的主题是很有压力的···

**Comment by qiansen1386** [comment]
有一个比较好的解决办法是，你先Fork这个主题，找到image文件夹。
然后果断把里面的花都换掉……

作者是小女纸，貌似非常喜欢花啊233333

**Comment by qiansen1386** [comment]
关于文字不能居中的问题，我想回家试玩一下，再给你回复。

**Comment by Aivier** [comment]
我不清楚你是用了什么导致了这个问题，干净的环境是不会有这两个问题的，检查一下你的插件
